spring.application.name=backend

#DB INFO
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#File size
spring.servlet.multipart.max-file-size=50MB

#server
server.port=8080

openrouter.api-key=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
spring.ai.google.genai.api-key=${GEMINI_API_KEY2}
gemini.chat.api-key=${GEMINI_API_KEY2}
spring.ai.google.genai.api-version=v1
spring.ai.google.genai.chat.options.model=gemini-3-flash-preview
groq.api-key=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

logging.level.org.springframework.ai=DEBUG
logging.level.org.springframework.web.client=DEBUG
logging.level.org.springframework.http=DEBUG
